name = "elementary-grade-worker"
main = "src/worker.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

[vars]
JWT_SECRET = "YOUR_HIGHLY_SECRET_KEY"

[[d1_databases]]
binding = "DB"
database_name = "class-py"
database_id = "2fd2778c-b7a1-4d87-bdba-799c23822d55"

[[r2_buckets]]
binding = "ASSET_BUCKET"
bucket_name = "class-py"

[ai]
binding = "AI"

[site]
bucket = "./dist"